name: Garmin Weight Sync

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Run SmartScaleConnect
        uses: docker://ghcr.io/alexxit/smartscaleconnect:master
        env:
          XIAOMI_USER: ${{ secrets.XIAOMI_USER }}
          XIAOMI_PASS: ${{ secrets.XIAOMI_PASS }}
          GARMIN_USER: ${{ secrets.GARMIN_USER }}
          GARMIN_PASS: ${{ secrets.GARMIN_PASS }}
